# .github/workflows/deploy.yaml

name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: huankong233/hk-vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_SCRIPT: cd ./packages/docs && npm install pnpm -g && pnpm install && pnpm run docs:build
          BUILD_DIR: src/.vitepress/dist
          TARGET_REPO: huankong-team/atri
          TARGET_BRANCH: docs
          COMMIT_MESSAGE: 自动打包完成
          CNAME: atri.huankong.top
